version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - release_version=docker-compose
    image: echo-bot
    ports:
      - 8080:8080
      - 8081:8081
      - 8082:8082
    environment:
      - DB_URL=jdbc:postgresql://db:5432/echodb
      - DB_USER=echo-user
      - DB_PASSWORD=db-s3cret!
      - SERVICE_TOKEN=this_is_some_secret
      - WIRE_API_HOST=https://prod-nginz-https.wire.com
    depends_on:
      - db

  db:
    image: postgres:13.1
    # just for local development
    environment:
      - POSTGRES_USER=echo-user
      - POSTGRES_PASSWORD=db-s3cret!
      - POSTGRES_DB=echodb
    ports:
      - 5432:5432
    volumes:
      - echo-bot-db:/var/lib/postgresql/data/

volumes:
  echo-bot-db:
