name: Release Pipeline

on:
  release:
    types: published

env:
  DOCKER_IMAGE: wire-bot/echo-bot
  SERVICE_NAME: echo

jobs:
  deploy:
    name: Build and deploy service
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set Release Version
        # use latest tag as release version
        run: echo ::set-env name=RELEASE_VERSION::${GITHUB_REF:10}

      - name: Build and publish docker image
        uses: docker/build-push-action@v1
        with:
          # set docker image
          repository: ${{ env.DOCKER_IMAGE }}
          # use GCR repository
          registry: eu.gcr.io
          # see https://github.com/marketplace/actions/docker-build-push#google-container-registry-gcr
          username: _json_key
          password: ${{ secrets.GCR_ACCESS_JSON }}
          # pass release_version
          build_args: release_version=${{ env.RELEASE_VERSION }}
          # tag the image with latest git tag
          tag_with_ref: true
          # add labels based on the build - see https://github.com/opencontainers/image-spec/blob/master/annotations.md
          add_git_labels: true
          # push only if this is tagged release
          push: ${{ startsWith(github.ref, 'refs/tags/') }}

      # Checkout our Kubernetes configuration
      - name: Checkout Rubicon
        uses: actions/checkout@v2
        with:
          repository: zinfra/rubicon
          # currently main branch is develop
          ref: develop
          path: rubicon
          # private repo so use different git token
          token: ${{ secrets.RUBICON_GIT_TOKEN }}

      # Update version to the one that was just built
      - name: Change Version in Rubicon
        env:
          IMAGE: ${{ env.DOCKER_IMAGE }}
          SERVICE: ${{ env.SERVICE_NAME }}
          VERSION: ${{ env.RELEASE_VERSION }}
        run: |
          # go to directory with configuration
          cd "rubicon/prod/services/$SERVICE"
          # escape literals for the sed and set output with GCR
          export SED_PREPARED=$(echo $IMAGE  | awk '{ gsub("/", "\\/", $1); print "eu.gcr.io\\/"$1 }')
          # update final yaml
          sed -i".bak" "s/image: $SED_PREPARED.*/image: $SED_PREPARED:$VERSION/g" "$SERVICE.yaml"
          # delete bakup file
          rm "$SERVICE.yaml.bak"

      # Setup gcloud CLI
      - name: Setup Google Cloud CLI
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '286.0.0'
          service_account_email: kubernetes-deployment-agent@wire-bot.iam.gserviceaccount.com
          service_account_key: ${{ secrets.GKE_SA_KEY }}
          project_id: wire-bot

      # Configure Docker to use the gcloud command-line tool
      - name: Configure Docker Google cloud
        run: |
          gcloud --quiet auth configure-docker

      # Get the GKE credentials so we can deploy to the cluster
      - name: Obtain k8s credentials
        env:
          GKE_CLUSTER: anayotto
          GKE_ZONE: europe-west1-c
        run: |
          gcloud container clusters get-credentials "$GKE_CLUSTER" --zone "$GKE_ZONE"

      # K8s is set up, deploy the app
      - name: Deploy the Service
        env:
          SERVICE: ${{ env.SERVICE_NAME }}
        run: |
          kubectl apply -f "rubicon/prod/services/$SERVICE/$SERVICE.yaml"

      # Commit all data to Rubicon and open PR
      - name: Create Rubicon Pull Request
        uses: peter-evans/create-pull-request@v2
        with:
          path: rubicon
          branch: ${{ env.SERVICE_NAME }}-release
          token: ${{ secrets.RUBICON_GIT_TOKEN }}
          labels: version-bump, automerge
          title: ${{ env.SERVICE_NAME }} release ${{ env.RELEASE_VERSION }}
          commit-message: ${{ env.SERVICE_NAME }} version bump to ${{ env.RELEASE_VERSION }}
          body: |
            This is automatic version bump from the pipeline.

      # Send webhook to Wire using Slack Bot
      - name: Webhook to Wire
        uses: 8398a7/action-slack@v2
        with:
          status: ${{ job.status }}
          author_name: ${{ env.SERVICE_NAME }} release pipeline
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.WEBHOOK_RELEASE }}
        # Notify every release
        if: always()
